spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/houssamlambara/streamify-config
          default-label: main

server:
  port: 8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false